DROP TABLE IF EXISTS books_users;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS users;

DROP SEQUENCE IF EXISTS author_id_seq;

DROP SEQUENCE IF EXISTS book_id_seq;

DROP SEQUENCE IF EXISTS users_id_seq;


CREATE SEQUENCE author_id_seq START WITH 1;

CREATE SEQUENCE book_id_seq START WITH 1;

CREATE SEQUENCE users_id_seq START WITH 1;

CREATE TABLE authors
(
    id          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  varchar(100)                             NOT NULL,
    second_name varchar(100)                             NOT NULL,
    third_name  varchar(100),
    CONSTRAINT pk_author_id PRIMARY KEY (id)
);

CREATE TABLE books
(
    id        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      varchar(100)                             NOT NULL,
    author_id integer                                  NOT NULL,
    CONSTRAINT pk_book_id PRIMARY KEY (id)
);

CREATE TABLE users
(
    id      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    varchar(120)                             NOT NULL,
    email   varchar(220)                             NOT NULL,
    country varchar(120),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE books_users
(
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    CONSTRAINT pk_book_id_user_id PRIMARY KEY (user_id, book_id)
);

ALTER TABLE books ADD CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES authors (id);

ALTER TABLE books_users ADD CONSTRAINT fk_users_books_users FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE books_users ADD CONSTRAINT fk_users_books_books FOREIGN KEY (book_id) REFERENCES books (id);

INSERT INTO authors(first_name, second_name, third_name)
VALUES ('Abel', 'Latoya', 'Abraham');
INSERT INTO authors(first_name, second_name, third_name)
VALUES ('Lawanda', 'Alice', 'Arthur');
INSERT INTO books(name, author_id)
VALUES ('The Pilgrim’s Progress', 1);
INSERT INTO books(name, author_id)
VALUES ('Robinson Crusoe', 1);
INSERT INTO books(name, author_id)
VALUES ('Gulliver’s Travels', 2);

INSERT INTO users(name, email, country)
VALUES ('Robbie Baird', 'yyax5@d-tk--.com', 'SYR');
INSERT INTO users(name, email, country)
VALUES ('Carla Compton', 'ctuf.qacaf@k-n--z.net', 'LTU');
INSERT INTO users(name, email, country)
VALUES ('Heath Stafford', 'bovq@xmm--s.com', null);

INSERT INTO books_users(book_id, user_id)
VALUES (1, 1);
INSERT INTO books_users(book_id, user_id)
VALUES (3, 1);
INSERT INTO books_users(book_id, user_id)
VALUES (1, 2);
INSERT INTO books_users(book_id, user_id)
VALUES (2, 2);
INSERT INTO books_users(book_id, user_id)
VALUES (2, 3);
INSERT INTO books_users(book_id, user_id)
VALUES (3, 3);
