DROP TABLE IF EXISTS books_users;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS billing_details;
DROP TABLE IF EXISTS credit_card;
DROP TABLE IF EXISTS bank_account;
DROP TABLE IF EXISTS users;

DROP SEQUENCE IF EXISTS author_id_seq;

DROP SEQUENCE IF EXISTS book_id_seq;

DROP SEQUENCE IF EXISTS users_id_seq;

DROP SEQUENCE IF EXISTS billing_id_seq;

CREATE SEQUENCE IF NOT EXISTS author_id_seq START WITH 1;

CREATE SEQUENCE IF NOT EXISTS book_id_seq START WITH 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1;

CREATE SEQUENCE IF NOT EXISTS billing_id_seq START WITH 1;


CREATE TABLE authors
(
    id          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  varchar(100)                             NOT NULL,
    second_name varchar(100)                             NOT NULL,
    third_name  varchar(100),
    CONSTRAINT pk_author_id PRIMARY KEY (id)
);

CREATE TABLE books
(
    id        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      varchar(100)                             NOT NULL,
    author_id integer                                  NOT NULL,
    CONSTRAINT pk_book_id PRIMARY KEY (id)
);

CREATE TABLE users
(
    id      integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    varchar(120)                             NOT NULL,
    email   varchar(220)                             NOT NULL,
    country varchar(120),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE books_users
(
    user_id integer NOT NULL,
    book_id integer NOT NULL,
    CONSTRAINT pk_books_rating_user_id PRIMARY KEY (user_id, book_id)
);

CREATE  TABLE billing_details (
                                  id                   bigint DEFAULT nextval('billing_id_seq') NOT NULL ,
                                  "owner"              varchar(100)  NOT NULL ,
                                  user_id              integer  NOT NULL ,
                                  CONSTRAINT pk_bank_account_id_0 PRIMARY KEY ( id )
);

CREATE  TABLE credit_card (
                              id                   bigint DEFAULT nextval('billing_id_seq') NOT NULL ,
                              card_number          varchar(20)  NOT NULL ,
                              exp_month            varchar  NOT NULL ,
                              exp_year             varchar  NOT NULL ,
                              CONSTRAINT pk_bank_account_id_1 PRIMARY KEY ( id )
);

CREATE  TABLE bank_account (
                               id                   bigint DEFAULT nextval('billing_id_seq') NOT NULL ,
                               bank_name            varchar(100)  NOT NULL ,
                               account              bigint  NOT NULL ,
                               CONSTRAINT pk_bank_account_id PRIMARY KEY ( id )
);

ALTER TABLE books ADD CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES authors (id);

ALTER TABLE books_users ADD CONSTRAINT fk_users_books_users FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE books_users ADD CONSTRAINT fk_users_books_books FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE billing_details ADD CONSTRAINT fk_billing_details_users FOREIGN KEY ( user_id ) REFERENCES users( id );

ALTER TABLE bank_account ADD CONSTRAINT fk_bank_account FOREIGN KEY ( id ) REFERENCES billing_details( id );

ALTER TABLE credit_card ADD CONSTRAINT fk_bank_account_0 FOREIGN KEY ( id ) REFERENCES billing_details( id );